

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = --html=reports/report.html --self-contained-html --json-report --json-report-file=reports/report.json
asyncio_mode = auto
log_cli = true
log_cli_level = INFO
